Properly instantiate icu

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -675,6 +675,12 @@ LUA_SHORT_VERSION
 LUA_VERSION
 LUA
 OTHER_OBJS
+ICU_LIBS
+ICU_CXXFLAGS
+ICU_CFLAGS
+ICU_CPPFLAGS
+PKG_CONFIG
+ICU_CONFIG
 MODE
 SYMLINK
 LIBNAME
@@ -5431,64 +5437,6 @@ fi
 
 fi
 
-if test "$enable_widechar" = "yes"; then
-    ac_fn_c_check_header_compile "$LINENO" "wchar.h" "ac_cv_header_wchar_h" "$ac_includes_default"
-if test "x$ac_cv_header_wchar_h" = xyes
-then :
-  printf "%s\n" "#define HAVE_WCHAR_H 1" >>confdefs.h
-
-fi
-ac_fn_c_check_header_compile "$LINENO" "wctype.h" "ac_cv_header_wctype_h" "$ac_includes_default"
-if test "x$ac_cv_header_wctype_h" = xyes
-then :
-  printf "%s\n" "#define HAVE_WCTYPE_H 1" >>confdefs.h
-
-fi
-
-    { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for main in -licuuc" >&5
-printf %s "checking for main in -licuuc... " >&6; }
-if test ${ac_cv_lib_icuuc_main+y}
-then :
-  printf %s "(cached) " >&6
-else $as_nop
-  ac_check_lib_save_LIBS=$LIBS
-LIBS="-licuuc  $LIBS"
-cat confdefs.h - <<_ACEOF >conftest.$ac_ext
-/* end confdefs.h.  */
-
-
-int
-main (void)
-{
-return main ();
-  ;
-  return 0;
-}
-_ACEOF
-if ac_fn_c_try_link "$LINENO"
-then :
-  ac_cv_lib_icuuc_main=yes
-else $as_nop
-  ac_cv_lib_icuuc_main=no
-fi
-rm -f core conftest.err conftest.$ac_objext conftest.beam \
-    conftest$ac_exeext conftest.$ac_ext
-LIBS=$ac_check_lib_save_LIBS
-fi
-{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $ac_cv_lib_icuuc_main" >&5
-printf "%s\n" "$ac_cv_lib_icuuc_main" >&6; }
-if test "x$ac_cv_lib_icuuc_main" = xyes
-then :
-
-printf "%s\n" "#define WIDECHAR 1" >>confdefs.h
-
-else $as_nop
-  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: WARNING: libicuuc not found.. disabling widechar support." >&5
-printf "%s\n" "$as_me: WARNING: libicuuc not found.. disabling widechar support." >&2;}
-fi
-
-fi
-
 { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for inflate in -lz" >&5
 printf %s "checking for inflate in -lz... " >&6; }
 if test ${ac_cv_lib_z_inflate+y}
@@ -6276,6 +6224,217 @@ printf "%s\n" "#define NO_PROCESS 1" >>confdefs.h
 if test "$enable_float"   = "no"; then
 printf "%s\n" "#define NO_FLOAT 1" >>confdefs.h
     fi
+
+if test "$enable_widechar" = "yes"; then
+
+  succeeded=no
+
+  if test -z "$ICU_CONFIG"; then
+    # Extract the first word of "icu-config", so it can be a program name with args.
+set dummy icu-config; ac_word=$2
+{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for $ac_word" >&5
+printf %s "checking for $ac_word... " >&6; }
+if test ${ac_cv_path_ICU_CONFIG+y}
+then :
+  printf %s "(cached) " >&6
+else $as_nop
+  case $ICU_CONFIG in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_ICU_CONFIG="$ICU_CONFIG" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  case $as_dir in #(((
+    '') as_dir=./ ;;
+    */) ;;
+    *) as_dir=$as_dir/ ;;
+  esac
+    for ac_exec_ext in '' $ac_executable_extensions; do
+  if as_fn_executable_p "$as_dir$ac_word$ac_exec_ext"; then
+    ac_cv_path_ICU_CONFIG="$as_dir$ac_word$ac_exec_ext"
+    printf "%s\n" "$as_me:${as_lineno-$LINENO}: found $as_dir$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+  done
+IFS=$as_save_IFS
+
+  test -z "$ac_cv_path_ICU_CONFIG" && ac_cv_path_ICU_CONFIG="no"
+  ;;
+esac
+fi
+ICU_CONFIG=$ac_cv_path_ICU_CONFIG
+if test -n "$ICU_CONFIG"; then
+  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $ICU_CONFIG" >&5
+printf "%s\n" "$ICU_CONFIG" >&6; }
+else
+  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: no" >&5
+printf "%s\n" "no" >&6; }
+fi
+
+
+  fi
+
+  if test -z "$PKG_CONFIG"; then
+    # Extract the first word of "pkg-config", so it can be a program name with args.
+set dummy pkg-config; ac_word=$2
+{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for $ac_word" >&5
+printf %s "checking for $ac_word... " >&6; }
+if test ${ac_cv_path_PKG_CONFIG+y}
+then :
+  printf %s "(cached) " >&6
+else $as_nop
+  case $PKG_CONFIG in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_PKG_CONFIG="$PKG_CONFIG" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  case $as_dir in #(((
+    '') as_dir=./ ;;
+    */) ;;
+    *) as_dir=$as_dir/ ;;
+  esac
+    for ac_exec_ext in '' $ac_executable_extensions; do
+  if as_fn_executable_p "$as_dir$ac_word$ac_exec_ext"; then
+    ac_cv_path_PKG_CONFIG="$as_dir$ac_word$ac_exec_ext"
+    printf "%s\n" "$as_me:${as_lineno-$LINENO}: found $as_dir$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+  done
+IFS=$as_save_IFS
+
+  test -z "$ac_cv_path_PKG_CONFIG" && ac_cv_path_PKG_CONFIG="no"
+  ;;
+esac
+fi
+PKG_CONFIG=$ac_cv_path_PKG_CONFIG
+if test -n "$PKG_CONFIG"; then
+  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $PKG_CONFIG" >&5
+printf "%s\n" "$PKG_CONFIG" >&6; }
+else
+  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: no" >&5
+printf "%s\n" "no" >&6; }
+fi
+
+
+  fi
+
+  if test "$ICU_CONFIG" = "no" && test "$PKG_CONFIG" = "no" ; then
+    echo "*** Neither icu-config nor pkg-config could not be found. Make sure either is"
+    echo "*** in your path, and that taglib is properly installed."
+    echo "*** Or see http://ibm.com/software/globalization/icu/"
+  fi
+
+  if test "$ICU_CONFIG" != "no" ; then
+    ICU_VERSION=`$ICU_CONFIG --version`
+    { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for ICU >= 1 via icu-config" >&5
+printf %s "checking for ICU >= 1 via icu-config... " >&6; }
+        VERSION_CHECK=`expr $ICU_VERSION \>\= 1`
+        if test "$VERSION_CHECK" = "1" ; then
+            { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: yes" >&5
+printf "%s\n" "yes" >&6; }
+            succeeded=yes
+
+            { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking ICU_CPPFLAGS" >&5
+printf %s "checking ICU_CPPFLAGS... " >&6; }
+            ICU_CPPFLAGS=`$ICU_CONFIG --cppflags`
+            { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $ICU_CPPFLAGS" >&5
+printf "%s\n" "$ICU_CPPFLAGS" >&6; }
+
+            { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking ICU_CFLAGS" >&5
+printf %s "checking ICU_CFLAGS... " >&6; }
+            ICU_CFLAGS=`$ICU_CONFIG --cflags`
+            { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $ICU_CFLAGS" >&5
+printf "%s\n" "$ICU_CFLAGS" >&6; }
+
+            { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking ICU_CXXFLAGS" >&5
+printf %s "checking ICU_CXXFLAGS... " >&6; }
+            ICU_CXXFLAGS=`$ICU_CONFIG --cxxflags`
+            { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $ICU_CXXFLAGS" >&5
+printf "%s\n" "$ICU_CXXFLAGS" >&6; }
+
+            { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking ICU_LIBS" >&5
+printf %s "checking ICU_LIBS... " >&6; }
+            ICU_LIBS=`$ICU_CONFIG --ldflags`
+            { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $ICU_LIBS" >&5
+printf "%s\n" "$ICU_LIBS" >&6; }
+        else
+            ICU_CPPFLAGS=""
+            ICU_CFLAGS=""
+            ICU_CXXFLAGS=""
+            ICU_LIBS=""
+            ## If we have a custom action on failure, don't print errors, but
+            ## do set a variable so people can do so.
+
+        fi
+  fi
+
+  if test "$succeeded" != "yes" && test "$PKG_CONFIG" != "no" ; then
+    { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for ICU >= 1 via pkg-config" >&5
+printf %s "checking for ICU >= 1 via pkg-config... " >&6; }
+        if $PKG_CONFIG --atleast-version=1 icu-i18n ; then
+            { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: yes" >&5
+printf "%s\n" "yes" >&6; }
+            succeeded=yes
+
+            { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking ICU_CPPFLAGS" >&5
+printf %s "checking ICU_CPPFLAGS... " >&6; }
+            ICU_CPPFLAGS=`$PKG_CONFIG --variable=CPPFLAGS icu-i18n`
+            { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $ICU_CPPFLAGS" >&5
+printf "%s\n" "$ICU_CPPFLAGS" >&6; }
+
+            { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking ICU_CFLAGS" >&5
+printf %s "checking ICU_CFLAGS... " >&6; }
+            ICU_CFLAGS=`$PKG_CONFIG --cflags icu-i18n`
+            { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $ICU_CFLAGS" >&5
+printf "%s\n" "$ICU_CFLAGS" >&6; }
+
+            { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking ICU_CXXFLAGS" >&5
+printf %s "checking ICU_CXXFLAGS... " >&6; }
+            ICU_CXXFLAGS=`$PKG_CONFIG --variable=CXXFLAGS icu-i18n`
+            { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $ICU_CXXFLAGS" >&5
+printf "%s\n" "$ICU_CXXFLAGS" >&6; }
+
+            { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking ICU_LIBS" >&5
+printf %s "checking ICU_LIBS... " >&6; }
+            ICU_LIBS=`$PKG_CONFIG --libs icu-i18n`
+            { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $ICU_LIBS" >&5
+printf "%s\n" "$ICU_LIBS" >&6; }
+        else
+            ICU_CPPFLAGS=""
+            ICU_CFLAGS=""
+            ICU_CXXFLAGS=""
+            ICU_LIBS=""
+            ## If we have a custom action on failure, don't print errors, but
+            ## do set a variable so people can do so.
+
+        fi
+  fi
+
+  if test "$succeeded" = "yes"; then
+
+
+
+
+
+
+printf "%s\n" "#define WIDECHAR 1" >>confdefs.h
+
+
+  else
+     { printf "%s\n" "$as_me:${as_lineno-$LINENO}: WARNING: libicuuc not found.. disabling widechar support." >&5
+printf "%s\n" "$as_me: WARNING: libicuuc not found.. disabling widechar support." >&2;}
+  fi
+
+        fi
 
 CPPFLAGS="${CPPFLAGS} -DDATADIR=\${datadir}"
 
